name: Build and Archive My Code

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Build
      run: go mod tidy && go build -o ansible-inventory main.go

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: ansible-inventory
        path: ansible-inventory
